### ISSUE TITLE
problem to limit producers time without inspection

### ISSUE THREAD

**Issue by rav-andre** [Sintrop/regeneration-credit#189]
Our goal is to develop a logic to only distribute tokens to producers that were inspected in the last 12 eras. If a producer stays more than 12 eras without inspection, he must not receive tokens. Right now we have a require that do not allow this producer to withdraw but he will keep getting the rights and once inspected again he will receive all the tokens. The problem is that, since it's a future action, the way it is now we can't change the state without paying. So we must think in a different way to do it.

**Comment by everson-ever** [comment]
Ainda temos esse problema?

**Comment by rav-andre** [comment]
> Ainda temos esse problema?

Não, foi resolvido com a nova lógica das eras. Vou fechar essa issue.
