### ISSUE TITLE
Validators logic

### ISSUE THREAD

**Issue by rav-andre** [Sintrop/regeneration-credit#203]
This issue is the implementation of the validators logic.

This user group will have a special action of voting to exclude users. 

1) Rename 'contributor' to 'validator'

2) Add a _banned_ bool type to users. When it is true, the user can't realize actions in the system anymore.

3) Variables

validatorsCount
votesToExclude = validatorsCount / 2

3) Create a function to vote do exclude a user.

- Must be a validator to call.
- The function must check how many validators exists in that moment. 
- Only one vote per validator

Add 1 vote, and If the user has less votes then _votesToExclude_.
Add 1 vote, and if the user has more votes then _votesToExclude_, change his _banned bool_ to true.

For example, let's imagine a situation where exists 12 validators.

When validator 1 votes, userVotes must be 1 and banned = false
When validator 2 votes, userVotes must be 2 and banned = false
When validator 3 votes, userVotes must be 3 and banned = false
When validator 4 votes, userVotes must be 4 and banned = false
When validator 5 votes, userVotes must be 5 and banned = false
When validator 6 votes, userVotes must be 6 and banned = true

**Comment by rav-andre** [comment]
Esboço do front-end:

## Inspeções
![image](https://github.com/Sintrop/core-contracts/assets/79549809/7cb7c31d-a01c-4eac-adfd-3194e72ed03d)

Validadores com a opção de votar para invalidar uma inspeção. Para invalidar, será necessário possuir 50% de votos. Ou seja, se o Sistema tiver 14 validadores, será necessário 7 votos. No sétimo, a inspeção deverá ser alterada para o status 'inválida' e seus dados devem ser removidos do isa do produtor e quantidade de inspeções do ativista. 

Poderia ser criado um atributo aos usuários que registrasse a quantidade de invalidações que um usuário recebeu.

## Usuários
![image](https://github.com/Sintrop/core-contracts/assets/79549809/4cde7273-c0de-41db-b6b4-50dbfef48c08)

Mesma ideia para os usuários. Validadores com a opção de votar para excluir um usuário. Para exclusão, será necessário possuir 50% dos votos novamente. Ao receber o voto de exclusão, o isa do produtor deverá ser removido da pool e o usuário não poderá mais interagir com nenhuma função do Sistema.

**Comment by everson-ever** [comment]
### Carregar contratos
```js
var validatorContract = await ValidatorContract.deployed()
var producerContract = await ProducerContract.deployed()
var activistContract = await ActivistContract.deployed()
var sintrop = await Sintrop.deployed()
var producerPool = await ProducerPool.deployed()
```


### 1 Requisitando inpeções com o produtor
```js
await sintrop.requestInspection({ from: accounts[1] })
```

### 2  Aceitando inspeção do produtor e realizando
```js
await sintrop.acceptInspection(1, { from: accounts[3] })
await sintrop.realizeInspection(1, [{categoryId: 1, isaIndex: 0, report: "Solo A totalmente sustentável", indicator: 8}], { from: accounts[3] })
```

### 3 Checando total de validadores 
```js
var validatorsCount = await validatorContract.validatorsCount()
validatorsCount.toString()
```

### 3 Adicionando validações para o produtor (Deve ter a metade de validadores ou mais para banir um usuário)
```js
  await validatorContract.addValidation(accounts[1], "Validator 8", { from: accounts[8] })
  await validatorContract.addValidation(accounts[1], "Validator 9", { from: accounts[9] })
```

### 4 Checando levels do produtor
```js
  await producerContract.getProducer(accounts[1])

  var eraLevels = await producerPool.eraLevels(1, accounts[1])
  eraLevels.toString()
```
