### ISSUE TITLE
Create invitation system

### ISSUE THREAD

**Issue by rav-andre** [Sintrop/regeneration-credit#219]
Create the invitation system. The logic will be posted on whitepaper.

## Code idea

producersCount;
inspectorsCount;
activistsCount;
researchersCount;
developersCount;
validatorsCount;

inpectorProducerRatio;
researcherProducerRatio;
developerProducerRatio;

blocksToInviteProducer;
blocksToInviteInspector;

constructor(uint256 _blocksToInviteProducer) {
    _blocsToInviteProducer = blocksToInviteProducer;
    _blocsToInviteInspector = blocksToInviteProducer;

}

function inviteProducer() requireActivist {
    require(canInviteProducer());
    //acessar atributo ativista
    activist.producerLastInvitedAt = block.number;

}

function canInviteProducer() internal {
    block.number > producerLastInvitedAt + blocksToInviteProducer; 
}

function inviteInspector() requireActivist {
    require(canInviteInspector());
    require(inspectorsCount > producersCount / ispectorProducerRatio);
    activist.inspectorLastInvitedAt = block.number;

}

function canInviteInspector() internal {
    block.number > producerLastInvitedAt + blocksToInviteProducer; 
}

function inviteResearcher() requireResearcher {
    require(researchersCount > producersCount / researcherProducerRatio);

}

function inviteDeveloper() requireDeveloper {
    require(developersCount > producersCount / developerProducerRatio);

}

**Comment by everson-ever** [comment]
A lógica dessa implementação está na página 14 do Whitepiper v1.6.1
[Sintrop_WhitePaper_-_v1.6.1_-_Portugues.pdf](https://github.com/Sintrop/core-contracts/files/13079685/Sintrop_WhitePaper_-_v1.6.1_-_Portugues.pdf)
